### ISSUE TITLE
Use contextIsolation

### ISSUE THREAD

**Issue by ZIMkaRU** [rocketlaunchr/electron-alert#10]
Hi)
It would be great to use contextIsolation flag to have the ability to use electron v12
https://github.com/electron/electron/issues/23506

```console
(node:8475) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by pjebs** [comment]
Let me adjust it

**Comment by pjebs** [comment]
What do you want done

**Comment by ZIMkaRU** [comment]
sorry for waiting for an answer, missed this
so I have just checked this alert with electron v12 and v13 and it works if add `contextIsolation: false` flag to `webPreferences` of `BrowserWindow` options: https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L288
info: https://github.com/electron/electron/issues/23506#issuecomment-780176437
I can send a PR if you want

**Comment by ZIMkaRU** [comment]
sent a PR https://github.com/rocketlaunchr/electron-alert/pull/11

**Comment by ZIMkaRU** [comment]
@pjebs

**Comment by pjebs** [comment]
I'll look at this in a few days

**Comment by ZIMkaRU** [comment]
Thanks

**Comment by pjebs** [comment]
Thanks for your contribution.

**Comment by pjebs** [comment]
Let me know if you are happy with changes.

**Comment by pjebs** [comment]
The library needs to be update to reflect v11 sweet alart 2 API. They have remove the v8 documentation online.

**Comment by ZIMkaRU** [comment]
> Let me know if you are happy with changes.

confirm, changes work fine for me on electron v13

**Comment by pjebs** [comment]
I'll be modifying API soon.

**Comment by ZIMkaRU** [comment]
Great, would be nice to do it with major version to have time to apply new api changes

**Comment by pjebs** [comment]
What other improvements and features should I add/make?
