### ISSUE TITLE
[Feature Request] Add options to inject css style

### ISSUE THREAD

**Issue by eslym** [rocketlaunchr/electron-alert#13]
maybe something like `alert.style = "* {font-family: sans-serif;}"`
then inject this style into the html

**Comment by pjebs** [comment]
https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L29

You should be able to inject using `head` in class conductor

**Comment by pjebs** [comment]
It must be an array contain your desired CSS that you want inside head tag

**Comment by pjebs** [comment]
https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L359

**Comment by pjebs** [comment]
Also, do you realise that the sweetalert2 API allows you to set css? You can read the docs there too

**Comment by eslym** [comment]
tried work around and work
