### ISSUE TITLE
bwOptions title fix

### ISSUE THREAD

**Issue by DMDComposer** [rocketlaunchr/electron-alert#18]
In the firewithFrame, shouldn't it be `bwOptions.title ? bwOptions.title` instead of `title  ? title`.  Believe its line 199

```js
bwOptions = Object.assign(bwOptions, {
			frame: true,
			transparent: false,
			thickFrame: true,
			closable: true,
			title: bwOptions.title ? bwOptions.title : "name" in app ? app.name : app.getName(),
		});
```

Otherwise, what you set in swalOptions as the title won't be transferred to the bwOptions.

**Comment by pjebs** [comment]
The actual firewithFrame function has a title argument.
The intention is that it takes precedent.

... but I think your idea is better.

I will update the version at some point with a brand new API that will actually just accept one object for all configuration. I'll fix issues like this then.
