### ISSUE TITLE
globalShortcut.registerAll is not a function

### ISSUE THREAD

**Issue by zensabbah** [rocketlaunchr/electron-alert#6]
Using this nice library I got the error in the object at line 373.
I changed the code removing registerAll and adding:

```
globalShortcut.register(
	"CommandOrControl+R",
	() => {}
);
globalShortcut.register(
	"CommandOrControl+Shift+R",
	() => {}
);

```
Now it seems working...which is the difference?

**Comment by pjebs** [comment]
What OS and electron version are you using?

**Comment by pjebs** [comment]
https://github.com/electron/electron/pull/20963

**Comment by zensabbah** [comment]
OSX Mojave and Electron 4.2.12

**Comment by pjebs** [comment]
I really don't know why this function doesn't exist for you. It's a recognised function in the API.

**Comment by zensabbah** [comment]
No idea dude!

**Comment by pjebs** [comment]
Have you thought about upgrading from v4?

**Comment by zensabbah** [comment]
I'm working in a project, maybe at the end, but thanks for the suggestion!

**Comment by pjebs** [comment]
I wrote this article: https://electron.guide/final-polish/renderer/#prevent-browserwindow-refreshes

I'm thinking of removing `globalShortcut` altogether from this library and instead requiring the user of the library to follow the instructions in the article instead.

**Comment by zensabbah** [comment]
Ok! Thanks a lot for your help!

**Comment by CaiProgramming** [comment]
can we get globalShortcut removed from the project please?

**Comment by pjebs** [comment]
What is your reasons for removing it?

**Comment by pjebs** [comment]
@CaiIsProgrammer a new version will allow `globalShortcut` to be removed when setting `bwOptions.noGlobalShortcut = true`
